name: CICD Api Develop

on:
  push:
    branches:
      - develop

jobs:
  build_push_deploy:
    name: Build -> Push -> Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Development
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME_DEVELOP }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG_DEVELOP }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: IMAGE_NAME,IMAGE_TAG
          script: |
            echo "IMAGE: $IMAGE_NAME:$IMAGE_TAG"
            cd greenskill-education-api
            git config --global user.email "bismika@amati.com"
            git config --global user.name "Bismika Amati"
            git fetch
            git pull origin develop --no-rebase
            sudo docker stop $IMAGE_NAME
            sudo docker rm $IMAGE_NAME
            sudo docker rmi $IMAGE_NAME:$IMAGE_TAG
            sudo docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
            sudo docker run \
              -e DATABASE_URL="postgres://postgres:oA{-vc.5\LJ=I.mq@34.101.88.251:5432/dev_db" \
              -e PORT=3000 \
              -e PROJECT_ID="bismika-amati" \
              -e PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC+OAl4lJTzB3bq\n7k2JKEnVJUxjSnTFZ5rjL3StIwgx7+P+Jx75oMf/1nCK9MdHZFgDhO0sri9z34XC\n2P3jSu38AY76XqGfTUNzua3lLqB2cVfBCES1HSyjOltoOvZJ0iNZp54gUaRlkHgq\nFioW+m3GGqmo9xXvzM8QF3GQwUe9/9MMmIN5hcXsbloL0oqtAT9mggOpTpIFWU95\no4pXZ+kAtEfseKcw7ypzkS2Hx6P0t6LoVpsoLTBfJF5EFIJwmeX3eRrNGdDW0vte\na2bo/RRAIXz0G/dBdSYEsKiKTJhly4CCVaM2ctchGKdLFAoPPywBrG44s7uk/6X5\ndYeGUFrRAgMBAAECggEAWMPAk67OVRyiHx5mOz98OMVHgLwRgr8GtcaC7XqADAGU\nhJjP6RBg1B/G8+knB0cplTbWELgV974SZusoiwT/yk4V4PsA89wzwlCe9+hKxAq/\nNxp7KYM8Pc1xM1H0dV1k1qUT8qP2kdiZYpZmPMPPLxdpHapz56vM4ob2HWU8a8oj\n/rQIAocQ4hXz2m1XrkVN0NZ5s7IGWSWJDRwKtvxuEF1r09qE0ftz66hX0rHRE2tg\nYGTxZS1BSfpUKLpa6yxFbnRRr2mVscJOY6Y5L/O2TWjKM4fJXQbYcNoswmHE3gHS\n8AxVMrhW3QuW+yKUqc234A6wgCw8AaofonhtgAznSwKBgQDomIK8VF6Pl3xFgiFb\nj3WPO3SEFCpjgxsDvsFi4S4tH2cA5QVBGc7hK3vNsHSy9fbASXQn8mTCYBpafCZi\n0vB26T1AOaE800n1LEzXDY85RHnSLXvBwc5PNBHfbsJkKC1HFdMvUpyIIyWR8vPH\n1lZfQKiQHFCpYVDGV4bLZVwS5wKBgQDRW+5P3n2MpnY8GFdrOrfQaUup7dUOavk2\n0Yvsf2ckEafqNQoYy1sEQDeIFm0UxRu8OLU5cCFdkzFjzl8S28i+cT/5qt6L0wSh\nYNPXY2r0/GQL/d53ut+VxauXiyj5omjF5TS08ok0VPssbMJvrk+TM9DfScNdBDgC\nh5W+weElhwKBgQCUY/BMXHszms6ivcGwW1cB+Ul9livw7szGV+Wiwsyl5vnc/T+b\n5+4vg4FpmaDqJ7ezt2kOrzsPMya9AaWvuKnHA0ibd+jhGF9/tjKTpMfyHjimGXRy\nCcYoi6y3Yj9MjMFOL6Na9pZ82Ad5FInovVq/TE3+GsJvPXG+CEsr6k+SkwKBgG9p\neLzQLgf3XdxFJ+BMcx1Zq4ZWppbxnoXppYjJk93B95XPe/wN2/W7JtIo/QuciVH0\n65wRa/AcMKBoZnfmtkGCiwUWRTArr78hhBqPMZAF8EfhZc5ZiDpv4wzWZYvTPeZy\nP0Y7+3/56WCO0DoWjQpM/M6Wtnx9jkDqXmoRSvtpAoGAecMs18cU3zVUgjrWuPmB\nLnRjOcAMgJ5s+EqSv24Re3aEJwTswg5chuNeOUDMO1FPe8qZzSZkZTgjKu3vDzfU\n1GUAsajKj44t5azjIhsCjO5m/zh+M29egEGrCC8qI6m7lRceE98BqAL7kQBsDHdO\nsz5RPdElQGtc8jgRySSA76I=\n-----END PRIVATE KEY-----\n" \
              -e CLIENT_EMAIL="630771281955-compute@developer.gserviceaccount.com" \
              -e STORAGE_MEDIA_BUCKET="greenskilleducation" \
              --name $IMAGE_NAME \
              -p 3002:3000 \
              -d $IMAGE_NAME:$IMAGE_TAG
