name: CICD Api Develop

on:
  push:
    branches:
      - develop

jobs:
  build_push_deploy:
    name: Build -> Push -> Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Development
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME_DEVELOP }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG_DEVELOP }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: IMAGE_NAME,IMAGE_TAG
          script: |
            echo "IMAGE: $IMAGE_NAME:$IMAGE_TAG"
            cd greenskill-education-api
            git config --global user.email "bismika@amati.com"
            git config --global user.name "Bismika Amati"
            git fetch
            git pull origin develop --no-rebase
            sudo docker stop $IMAGE_NAME
            sudo docker rm $IMAGE_NAME
            sudo docker rmi $IMAGE_NAME:$IMAGE_TAG
            sudo docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
            sudo docker run -e DATABASE_URL="postgres://bismika_usr:rahasia123@10.14.64.12:5432/dev_db" -e PORT=3000 --name $IMAGE_NAME -p 3002:3000 -d $IMAGE_NAME:$IMAGE_TAG
