name: CICD Frontend

on:
  push:
    branches:
      - develop

jobs:
  build_push_deploy:
    name: Build -> Push -> Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Production
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: IMAGE_NAME,IMAGE_TAG
          script: |
            echo "IMAGE: $IMAGE_NAME:$IMAGE_TAG"
            ls
