name: CICD Frontend

on:
  push:
    branches:
      - develop

jobs:
  build_push_deploy:
    name: Build -> Push -> Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Production
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: false
          envs: IMAGE_NAME,IMAGE_TAG
          script: |
            echo "IMAGE: $IMAGE_NAME:$IMAGE_TAG"
            cd greenskill-education-api
            git pull origin develop
            sudo docker stop $IMAGE_NAME
            sudo docker rm $IMAGE_NAME
            sudo docker rmi $IMAGE_NAME:$IMAGE_TAG
            sudo docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
            sudo docker run -e DATABASE_URL="postgres://bismika_usr:rahasia123@34.101.220.5:5432/bismika-dev?pool_timeout=0" -e PORT=3002 --name $IMAGE_NAME -p 3000:3002 -d $IMAGE_NAME:$IMAGE_TAG
